import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useUser } from '@auth0/nextjs-auth0';

const Home: NextPage = () => {
  const { isLoading, error, user } = useUser();

  console.log(user);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <a href="/api/auth/login?returnTo=/">Login</a>
      <a href="/api/auth/logout?returnTo=/">logout</a>
    </div>
  );
};

export default Home;
